# PORT FORWARDING
#
# 9000  Sonar
# 9010  Jenkins
# 9090  Adminer
# Postgres is not exposed

version: '2.4'
services:
  postgres:
    build:
      context: postgres/
    restart: unless-stopped
    networks:
      - default
    container_name: postgres
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - winnovator_postgresql:/var/lib/postgresql
      - winnovator_postgresql_data:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "9090:8080"
    networks:
      - default
    container_name: adminer
  sonarqube:
    build:
      context: sonarqube/
    restart: unless-stopped
    ports:
      - "9000:9000"
    networks:
      - default
    container_name: sonarqube
    environment:
      - sonar.jdbc.username=sonar
      - sonar.jdbc.password=sonar
      - sonar.jdbc.url=jdbc:postgresql://postgres:5432/sonar
    volumes:
      - winnovator_sonarqube_conf:/opt/sonarqube/conf
      - winnovator_sonarqube_data:/opt/sonarqube/data
      - winnovator_sonarqube_extensions:/opt/sonarqube/extensions
    depends_on:
      - postgres
    mem_limit: 4g
  jenkins:
    build:
      context: jenkins/
    restart: unless-stopped
    privileged: true
    user: root
    ports:
      - "9010:8080"
    networks:
      - default
    container_name: jenkins
    volumes:
      - winnovator_jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # Expose the docker daemon in the container
    depends_on:
      - sonarqube
    mem_limit: 4g
volumes:
  winnovator_sonarqube_conf:
  winnovator_sonarqube_data:
  winnovator_sonarqube_extensions:
  winnovator_postgresql:
  winnovator_postgresql_data:
  winnovator_jenkins_home:
